### ISSUE TITLE
List links 

### ISSUE THREAD

**Issue by novasdream** [APDA-HQ/APDA#14]
Bem galera não sei se estou com o usage correto mas acredito que não esteja funcionando da maneira correta a listagem de links.

Eu abri um issue no markup

https://github.com/github/markup/issues/439

**Comment by racerxdl** [comment]
Santa bizarrice o.O
É bug mesmo :octocat:

**Comment by guil-herm-e** [comment]
Boa @novasdream!

**Comment by novasdream** [comment]
Pronto agora temos  1 link la do markup  apontando para ca
