### ISSUE TITLE
Apps ou sites desenvolvidos

### ISSUE THREAD

**Issue by gabrielribeiro** [APDA-HQ/APDA#16]
Se eu desenvolver um app (ou site), posso postar o link pra galera (desde que seja sem fins lucrativos)?
Podemos definir isso nas regras do grupo?

**Comment by novasdream** [comment]
Sim ja esta definido nas ultimas regras ali na area do github

https://github.com/APDA-HQ/APDA#8-github

**Comment by gabrielribeiro** [comment]
3.2.3. Verdade.
