### ISSUE TITLE
Comportamento estranho.

### ISSUE THREAD

**Issue by novasdream** [APDA-HQ/APDA#23]
Bem pessoal..
Accessando o link pelo commit

https://github.com/APDA-HQ/APDA/commit/d8ea5298273bc750527469a2f68302f551df2da0
Certos comentarios aparecem.

E acessando pelo pullrequest 

https://github.com/APDA-HQ/APDA/pull/22

Alguns comentarios aparecem em ambos e outros não.. 
Esse comportamento deveria acontecer dessa maneira mesmo ?

**Comment by cyberglot** [comment]
Sim, um é comentário de commit e outro de issue/pr.

**Comment by novasdream** [comment]
E os comentarios deveriam agir dessa forma ?

**Comment by cyberglot** [comment]
sim.
