### ISSUE TITLE
Quebras de termos de uso.

### ISSUE THREAD

**Issue by juniorb2ss** [APDA-HQ/APDA#34]
Pedidos por ajuda com aplicações que quebrem os termos de uso de certos serviços, como por exemplo "spam" e "bot" podem ser feitos sem problema? Acredito ser incorreto moralmente um pedido desse. Não deveriamos nos preocupar com o que certas pessoas fazem, mas, se fosse um pedido para um serviço meu não gostaria que outros "especialistas" compartilhassem conhecimento incorreto no grupo. Implementar algo nas regras não poderia evitar? ou regulamentar.

**Comment by reinaldorauch** [comment]
+1

**Comment by rmrgh** [comment]
O [parágrafo 2](https://github.com/APDA-HQ/APDA#2---leis-regentes) pode ser adaptado para englobar esse tipo de problema.

**Comment by juniorb2ss** [comment]
@ramirio estou ciente, mas falando juridicamente termo de uso não é considerado como parte de "leis brasileiras", seria bom uma complementação.

**Comment by novasdream** [comment]
quem queria comprar bot para whatsapp ?

**Comment by juniorb2ss** [comment]
@novasdream não é compra, pedindo conhecimentos. Isso acontece repetida vezes no grupo. E uma galera ainda passa os links dos projetos que fazem isso.

**Comment by rmrgh** [comment]
Bom, eu particularmente não sou contra da galera pedir ajuda pra criar bot, até porque existem n serviços que permitem a criação de bots e n serviços q restringem, não tem como filtrar isso (não sou da moderação mas tô imaginando a situação).

**Comment by juniorb2ss** [comment]
@ramirio "É proibido pedidos que ferem os termos de uso de seus respectivos serviços. (EX: Bot para Whatsapp)"

Veja o pull.

**Comment by rmrgh** [comment]
@juniorb2ss Sim, eu vi o pull, a regra faz sentido mas é praticamente imoderavel, os termos de serviços variam muito entre as aplicações.

**Comment by juniorb2ss** [comment]
@ramirio sim, amigo. Por isso ta claro o "seus respectivos serviços". Atente-se. Maioria das regras não tem como moderar, por isso a comunidade precisa do apoio dos membros para reportar. Quando ver algo e saber que o serviço não permite aquilo, basta reportar.
