### ISSUE TITLE
Tem problema anunciar venda de livros usados?

### ISSUE THREAD

**Issue by reinaldorauch** [APDA-HQ/APDA#42]
Segue os links dos produtos no ML

[Livro do Pablo Dall'Oglio sobre PHPOO](http://produto.mercadolivre.com.br/MLB-808566272-php-prog-com-orientaco-a-objetos-2-edico-pablo-dalloglio-_JM)
[Livro do Maujor sobre javascript](http://produto.mercadolivre.com.br/MLB-808567351-javascript-guia-do-programador-mauricio-samy-silva-_JM)

**Comment by racerxdl** [comment]
Não tem problema, mas em ISSUE não é um bom lugar pra colocar livros usados.
