### ISSUE TITLE
Do tratamento específico para falantes de português não nativos do Brasil e que não tem acesso ao mesmo padrão de conexão com internet

### ISSUE THREAD

**Issue by fititnt** [APDA-HQ/APDA#43]
Um Angolano, que provavelmente tem a mesma internet que nós tínhamos até em grandes cidades no Brasil há 10~15 anos atrás, e que provavelmente pode usar por celular sem custos apenas Facebook e WhatsApp, fez uma pergunta que poderia ter sido melhor formulada.

**O que normalmente aconteceria**: alguém cordialmente explica pra ele como ele poderia melhorar a pergunta dele, e depois recomendaria apagar o tópico. Lembrando que **ele não conseguiria ler as regras do grupo porque elas estão aqui no Github, logo nem se ele quisesse ele teria acesso.**

**O que aconteceu**: algumas pessoas tentaram ajudar ele, de forma educada. Mas começaram a fazer bullyng. Então passaram a ir no perfil pessoal do angolano, fazer print e HUMILHAR o cara por ele, no perfil pessoal, falaram coisas que não pareciam fazer sentido para brasileiros.

Eu iniciei a discussão, que foi apagada. O print está abaixo, e recomendo a leitura em vez de eu repetir tudo aqui.

- PONTO 1: se não foi o próprio angolano que, humilhado, deletou o próprio post, **a pessoa moderadora BANIU ou não as pessoas que fizeram bullyng hardcore**? Relembrando: essas pessoas que se arrogam como programadores estavam indo até na vida pessoal do cara, pra reclamar que ele, de um celular, não escreve da mesma forma que o português do Brasil, e que ele não leu as regras que a operadora de celular dele não deixa liberado pra ele ver; Reclamaram também que ele pediu WhatsApp, confundindo ele com alguém "folgado" quando na verdade é bem comum em países que WhatsApp ou Facebook é liberado e que nem mesmo busca no Google é.
- PONTO 2: recomendo mudança explícita nas regras da APDA para citar que os outro 8 países que falam português mas não são o Brasil não podem exigir que a pessoa escreva perfeitamente; como referência, lembrem-se que _a maioria aqui são para Inglaterra o que os angolanos são para brasileiros_ quanto a questão de escrever bem.

Esse assunto é pertinente, pelo simples fato de que um programadores mais novos arrogantes, estão agindo de forma tão prepotente que humilham um não Brasileiro por coisas que desenvolvedores como eu, ou basicamente qualquer desenvolvedor de referência no Brasil, teriam sido humilhados há uma ou duas décadas atrás, quer fosse por baixa proficiência em inglês ou simplesmente por não ter internet muito melhor que uma discada.

![-1 a p d a associacao de programadores depressivos anonimos](https://cloud.githubusercontent.com/assets/812299/20324281/13e76b44-ab67-11e6-82d5-40430311410a.png)

**Comment by dansoah** [comment]
Acho que especificamente uma regra sobre outros países falantes do português não faz muito sentido, mas acho que vale reforçar as regras sobre "não seja um idiota".
Não foi só com esse angolano que eu vi esse tipo de coisa acontecer, tem muita gente que esquece que também não soube um dia como funciona o If e trata muito mal a galera que trás dúvidas mais simples para o grupo.

**Comment by v0idpwn** [comment]
Discordo. 
O grupo é brasileiro e, por consequência, seu idioma é o português brasileiro. Tanto o português de Portugal quanto suas variações não são a linguagem oficial do grupo. Reduzir todas as linguagens que se originaram do português a "formas diferentes de falar" é ignorância. 

Quanto ao bully**i**ng feito por alguns membros, este quebra regras já existentes, sem a necessidade da criação de novas. As regras têm cumprido sua função exatamente como o proposto.

**Comment by anabastos** [comment]
Concordo com o @dansoah e o @v0idpwn mas poucas pessoas são punidas por desrespeito ao próximo. As regras também dizem que erros de português deveriam ser tolerados.

**Comment by fititnt** [comment]
Se explicitamente a defesa, em especial que quem queria trollar o cara, era de que o grupo era para brasileiros, o correto seria deixar isso explícito nas regras de que **não falantes nativos de português do brasil não são bem vindos**. 

A forma como humilharam o cara foi brutal. Foi tão brutal, que eu não duvido que ele desista de interagir com brasileiros no futuro, ou mesmo desista de ser programador, em especial se alguém não for atrás do cara e explicar o que aconteceu.

**Comment by cyberglot** [comment]
se o grupo é brasileiro, tem que comunicar que estrangeiros não são bem-vindos.

edit: enfim, imagino como seria no SO se as pessoas tivessem obrigação de falar inglês certo.  ou mesmo um inglês específico.

**Comment by v0idpwn** [comment]
Errado. Assim como frequentamos comunidades americanas falando inglês, eles devem frequentar a comunidade brasileira se esforçando para falar o português do brasil e, principalmente, **respeitando as regras**, coisa que o post não fazia.

**Comment by fititnt** [comment]
@v0idpwn quais regras? A que uma pessoa com 3G, não só da Africa, mas até no Brasil, não consegue ler de uma 3G porque não está no Facebook?

**Comment by v0idpwn** [comment]
Ler as regras é um requisito para postar. Se não fosse, o grupo entraria em estado de anarquia. A "zoeira" feita pelos membros do grupo tem como finalidade alertar o usuário às regras. Certamente não é a forma mais saudável, mas é efetiva porque ser feita com tom de piada motiva membros comuns a fazê-lo. Se exageraram no zoar, isso se encaixa em outra regra.

Quanto a ele não conseguir ler as regras, pode-se providenciar que estas sejam legíveis dentro do grupo, no post fixado. Ainda assim, isso é um problema dele.

**Comment by fititnt** [comment]
Mesmo assumindo que _soft xenofobia_ é aceita, no estado atual devem ser proibida brasileiros que usam celular com 3G com banda liberada apenas pra Facebook/WhatsApp. Qual percentual da população brasileira dentro disso?

Princípio básico de UX: você não pode dar uma tarefa impossível para um usuário e esperar que ele consiga. E não ter nem conectividade é bem grave, não é nem questão de interface ruim.

Pra quem está reclamando, de uma olhada em http://www.measuringu.com/blog/rating-severity.php. Boa parte da população brasileira, inclusive programadores iniciantes fora do PC usando 3G pre-paga, não vão conseguir ver regras fora do facebook.

Jakob Nielsen diria que essa falha é catastrófica, e em nenhuma outra escala diriam que se encaixaria em algo que não seja o pior nível possível.

**Comment by cyberglot** [comment]
"Errado" 😂 pensa só os ingleses tendo que escrever no inglês americano só porque "a comunidade" é americana. isso é normativo e não faz sentido nenhum no contexto de linguagens naturais.

**Comment by v0idpwn** [comment]
@fititnt Esse "grave problema" poderia ser corrigido facilmente tornando as regras acessíveis no post pinado ou na descrição do grupo (como já esteve, se bem me lembro), sem necessidade de tratamento especial. Já havia falado sobre isso no comentário anterior.

@cyberglot Você realmente está comparando a relação inglês americano - inglês britânico a português brasileiro - português angolano? São casos totalmente diferentes. 

Edit: havia cometido um erro de interpretação, mas já fixei.

**Comment by MarcoWorms** [comment]
As pessoas estão erradas por zoar ele independente daonde o cara veio, agora, quanto à entender português diferente, eu não acho que precisa ser uma regra. Se a pessoa não tiver saco de entender a pergunta do cara ela pode simplesmente ignorar. Zoar quem postou e/ou postar foto do cara já é contra as regras de qualquer maneira.

*não vi o poste, comentei com base nos prints e nos comentários aqui :P

**Comment by racerxdl** [comment]
Eu geralmente nem comento aqui, mas sou obrigado a comentar agora:
1. Português Brasil, Português Portugal, Português _qualquer coisa_ é: Português. A gramática é unificada. Existem habitos diferentes (tipo em portugal usarem mais a segunda pessoa e não a primeira) e algumas inversões que **são válidas** no português brasil. Logo independente do grupo ser brasileiro deve-se respeitar o jeito do outro falar. Fala sério cara, a gente tem mais diferenças no jeito de falar aqui dentro do Brasil do que fora dele.
2. O acesso a internet não é desculpa, ele tem acesso ao facebook, logo a internet e ao tópico que está fixo dizendo pra ler as regras. Se ele não ler e desrespeitar, ele vai ser banido. **ponto final**.
3. Existe uma regra chamada **não seja idiota**. E além disso existe a cláusula **7** nas regras que diz exatamente sobre o respeito. Zoeira tem limites.
4. Eu não faço a mínima ideia do que aconteceu na APDA com esse angolano (nem sei quem é o cara). Só to respondendo baseado no que li aqui.

**Comment by Dkmister** [comment]
Complementando o que falaram já aqui , falta muita empatia de se colocar no lugar do outro. É bem fácil criticar e apontar dedos como se fosse o dono supremo da razão, enquanto todo mundo já passou por fases diferentes de conhecimento.

É muita falta de senso zoar alguém de outro paradigma cultural. É de certo modo um preconceito, até possivelmente passando dessa linha de ''**zoeira**'', para chegar até ser um cyber-bullying.

**Comment by fititnt** [comment]
https://www.facebook.com/groups/desenvolvimentoweb/permalink/1285232994868470/

![xenofobia](https://cloud.githubusercontent.com/assets/812299/21071892/c9be5454-be96-11e6-8593-df03311e792b.png)

---

Edit: são 5 horas da manhã de um sábado, só depois ví que era de **outro** grupo do Facebook, e não APDA, sobre pessoal fazendo comentários. Ainda assim é bizarro imaginar que tem colegas de profissão que em 2016 brincam de fazer piadinha com xenofobia em grandes grupos no Facebook.

**Comment by brunoventura** [comment]
@fititnt muito boa contribuição, estou participando dessa thread que você postou por último. Admito que sempre fico receoso ao postar em githubs de projetos onde a lingua nativa é o inglês, de parecer um sujeito "awkward" por falar de uma maneira primitiva, já que mesmo tendo uma certa proficiencia na linguagem, não seja minha lingua nativa. Se eu sofresse o que esse pessoal está sofrendo eu realmente me sentiria muito menos propicio a contribuir. 

Só gostaria que o pessoal pensasse nisso... E se fosse você tentando participar de um grupo formado apenas por nativos de países onde a lingua oficial é o ingles sofrendo bullyng???

São com atitudes como essa que fazem com que a área da tecnologia seja dominada pelo machismo, preconceito, falta de pluralidade cultural e étinica...

**Comment by davidbranco** [comment]
Acho que as regras já contemplam a necessidade solicitada acima.
A regra já diz que a zoeira tem limites, portanto, reportem as zoeiras além do limite.
Caso o Angolano tenha sido banido, eu irei dar unbanned.

**Comment by fititnt** [comment]
**Estamos fazendo algum progresso. Ainda existem referências ao que é criticado nesse issue, mas o fato de levar a publico o convite a se pensar o que é ou não aceitável, está fazendo MUITO mais gente moderar e educar quem faz alguma ofensa ou desmérito.**

E antes que alguém pergunte "ah, mas dai se não puder fazer piadas tratando como inferior cultura de outros países, não vamos poder zuar nem com favelado ou gente do nosso próprio país", eu diria isso seria ótimo.


https://www.facebook.com/groups/osadpa/permalink/1016989045073289/

---

- ...

![apda-comece-pela-linguagem-portugues](https://cloud.githubusercontent.com/assets/812299/21570475/8896f20c-cead-11e6-86c5-a0762b917f59.png)

----

- Referência de forma depreciativa a inteligência (algo artificial, não complexo como de um humano
- Assédio, referência a investigar a vida da pessoa não pertinente a pergunta, para tratar com desmétito ("vejam a timeline")

![apda-vejam-timeline-dele](https://cloud.githubusercontent.com/assets/812299/21570474/8895de12-cead-11e6-922b-f6cde419afa3.png)


---

- Despersonificação (um mascote não pode ser um humano)
- Assédio recorrente/persistente (para se tornar um mascote, é necessário ter merecido por recorrência

![apda-mascote-apda](https://cloud.githubusercontent.com/assets/812299/21570473/88956e64-cead-11e6-9d15-e254a3ade4dd.png)

---

Em todos os casos, diferente do de outro grupo que postei antes, parece ser menos sobre xenofobia, e muito, mas muito mais pelo lado de costume em ofender outras pessoas, como os próprios brasileiros. Creio que é muito mais sobre desinformação do que má fé.

**Comment by fititnt** [comment]
Atualização: o tópico citado no ponto anterior foi apagado e, após reclamação, a moderação da APDA explicitamente criou um post para deixar claro isso. O link como referência pra quem quiser usar é https://www.facebook.com/groups/osadpa/permalink/1017254311713429/

## Do primeiro incidente vs segundo incidente na APDA

Pra quem tiver interesse, mesmo com post apagado, houve uma mudança bem significativa no segundo incidente. Pessoas diferentes estavam convencendo os demais membros de que alguns comentários deles eram ruins, de modo que **alguns que fizeram piadas se desculparam, pois não sabiam que, por exemplo, a outra pessoa não era do Brasil, e passaram a interagir de forma construtiva**

OK que alguns aqui podem achar eu _bonzinho demais_, porém a não ser comentário nível de denunciar pro MPF, pode ser interessante deixar que os próprios membros se moderem. Eu já fui moderador, e isso ajuda até revanchismo contra moderação.

Problema de usar facebook como fórum é que ele acredito que ele ainda não opções mais avançadas como banir temporariamente e com mensagem explicativa. Isso economizaria muito tempo e seria algo intermediário entre deixar livre e banir.

## Para histórico futuro, como era postagem completa

https://www.facebook.com/groups/osadpa/permalink/643123495793181/

> Emerson Rocha Luiz 
> Quem foi o moderador que apagou o post em vez de remover os comentários?
> 37 min · Curtir · 1
> Moisés Matias
> Moisés Matias Vou abrir uma postagem direcionada a ajudar a galera dos países Lusófonos. quem quiser auxiliar, é bem vindo. Moderadores, por favor: Não a apaguem.
> 34 min · Curtir · 1
> Emerson Rocha Luiz
> Emerson Rocha Luiz Moisés Matias recomendo NÃO fazer isso até ter uma resposta formal da moderação desse grupo.
> 
> É uma falta de respeito com todos que estavam contribuindo de forma construtiva. Maioria aqui tem mais de 30, trabalha a sério na área, e está sendo tratado tratado como criança ao ter post inteiro deletado porque ALGUNS resolvem fazer piadinha.
> 32 min · Curtir · 2
> Moisés Matias
> Moisés Matias Sim, concordo com você Emerson. Queria cria-lo como forma a ajudar também e organizar o conhecimento para os rapazes lusófonos que estejam curiosos e dispostos a iniciar.
> 31 min · Curtir
> Guilherme Carlos
> Guilherme Carlos Alguém lembra quem foi o autor do post? To viajando então não tô acompanhando aqui. Mas podemos ver isso direito Paulo, David, Worms
> 30 min · Curtir · 2
> David Branco
> David Branco Depois eu checo nos logs da Administração. Enquanto isso, pode criar o tópico Moisés Matias. Use o gato dá seriedade e me marque caso encontre problemas.
> 29 min · Descurtir · 2
> Emerson Rocha Luiz
> Emerson Rocha Luiz Autor "Dalton Dos Santos"; conteúdo da postagem exato "Quero tanto aprender a programa"; o autor não interagiu de qualquer forma negativa com respostas feitas contra ele
> 
> Edit: é pelo menos a segunda vez que postagem dele (ao menos que eu vi) é apagada...Ver mais
> 23 min · Editado · Curtir · 2
> David Branco
> David Branco Obrigado Emerson Rocha Luiz. Eu fiz um meta post a respeito: https://m.facebook.com/groups/142918099147059?view=permalink&id=1017254311713429
