### ISSUE TITLE
sugestão: repositório awesome-apda

### ISSUE THREAD

**Issue by rmrgh** [APDA-HQ/APDA#47]
Um repositório estilo awesome-* contendo links de discussões que foram úteis e/ou que tem valor histórico dentro da APDA.

**Comment by davidbranco** [comment]
Boa man.
Garimpa e monta a lista pra nós.

**Comment by rmrgh** [comment]
O @evertonl1ma q manja dos posts históricos. Vou levantar com ele uma lista.

**Comment by evertonl1ma** [comment]
Eu vou dar uma olhada nos posts que tenho salvo aqui, e depois te passo.
